[package]
name = "reywen-txc"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bson = "2.5.0"
futures-util = "0.3.25"
mongodb = "2.3.1"
reqwest = "0.11.13"
reywen = "0.1.6"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
tokio = { version = "1.24.1", features = ["full"] }
urlencoding = "2.1.2"
